/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:725561ee-f6b2-4712-9d21-20a7858bf202",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1yEx7DMTS",
    "aws_user_pools_web_client_id": "4aivqa3osbcephddrp1pna7ejb",
    "oauth": {}
};


export default awsmobile;
